# CAT I
- name: "| HIGH | V-38666 | AUDIT |\n
        The system must use and update a DoD-approved virus scan program."
  command: /etc/init.d/nails status
  ignore_errors: yes
  always_run: yes
  changed_when: no
  register: av_nails_status_audit
  tags:
      - cat1
      - high
      - V-38666
      - antivirus
      - audit

- name: "| HIGH | V-38666 | AUDIT |\n
        The system must use and update a DoD-approved virus scan program. Checking Cron"
  shell: grep uvscan /etc/cron* /var/spool/cron/*
  register: av_uvscan_cron_audit
  ignore_errors: yes
  always_run: yes
  changed_when: no
  tags:
      - cat1
      - V-38666
      - antivirus
      - audit
      - high

- name: "| HIGH | V-38666 | AUDIT |\n
        The system must use and update a DoD-approved virus scan program. Looking for virus definitions older than seven days"
  command: find /usr/local/uvscan -type f -mtime +7
  register: av_defs_audit
  changed_when: no
  ignore_errors: yes
  always_run: yes
  tags:
      - cat1
      - V-38666
      - antivirus
      - high
      - audit

- name: "| HIGH | V-38677 | AUDIT |\n
        The NFS server must not have the insecure file locking option enabled"
  command: grep insecure_locks /etc/exports 
  register: nfs_insecure_locking_audit
  ignore_errors: yes
  changed_when: no
  always_run: yes
  tags:
      - cat1
      - high
      - V-38677
      - audit
      - nfs

# CAT II

# CAT III
- name: "| LOW | V-38455 | AUDIT |\n
        The system must use a separate file system for /tmp"
  shell: mount | grep "on /tmp "
  register: tmp_mounted_audit
  always_run: yes
  ignore_errors: yes
  changed_when: no
  tags: 
      - cat3
      - low
      - V-38455
      - partitions
      - audit

- name: "| LOW | V-38456 | AUDIT |\n  
        The system must use a separate file system for /var"
  shell: mount | grep "on /var "
  register: var_mounted_audit
  changed_when: no
  ignore_errors: yes
  always_run: yes
  tags:
      - cat3
      - V-38456
      - partitions
      - low
      - audit

- name: "| LOW | V-38463 | AUDIT |\n
        The system must use a separate file system for /var/log"
  shell: mount | grep "on /var/log "
  register: varlog_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - high
      - V-38463
      - partitions
      - audit

- name: "| LOW | V-38467 | AUDIT |\n
        The system must use a separate file system for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: varlogaudit_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - V-38467
      - partitions
      - audit

